G17: Add product definition
mtgjson/mtg-sealed-content pull request #161
Opened 2024-04-12 16:39 UTC by kodawah

2024-04-12 18:05 UTC, axxroytovu commented
The GHA check for a pull request shows if you formatted your yaml correctly. If the check fails you should automatically look for where your yaml is wrong.

2024-04-12 18:05 UTC, axxroytovu requested changes

2024-04-12 18:05 UTC, axxroytovu commented on data/contents/G17.yaml
> +      foil: true
Card is a top level key. Should be:
```
card:
- foil: true
  name: Plains
  ...
- foil: true
  name: Mountain
  ...
```

2024-04-12 21:18 UTC, kodawah commented on data/contents/G17.yaml
> +      foil: true
mb, fixed

2024-04-12 21:19 UTC, kodawah commented
I'm very glad for the GHA automation, but man i find yaml syntax SO odd 😅

2024-04-13 17:43 UTC, axxroytovu approved these changes

2024-04-13 17:43 UTC, merged