List all known SLD bonus cards in the product description
mtgjson/mtg-sealed-content pull request #195
Opened 2024-06-25 23:04 UTC by kodawah

This offers more control and ease of updating, as well as an attempt at taking variance into consideration (where needed).

2024-06-25 23:20 UTC, axxroytovu commented on data/contents/SLD.yaml
> +    card:
I think this card should be foil

2024-06-25 23:20 UTC, axxroytovu commented on data/contents/SLD.yaml
> +    - foil: true
Missing the `card:` line

2024-06-25 23:57 UTC, kodawah commented on data/contents/SLD.yaml
> +    - foil: true
✅

2024-06-25 23:58 UTC, kodawah commented on data/contents/SLD.yaml
> +    card:
actually no, Thought-Knot Seer is foil/nonfoil so it'd make sense that the nonfoil is found in the nonfoil bundle

2024-06-28 15:57 UTC, axxroytovu commented
I salute you for working on this o7

2024-07-06 00:20 UTC, kodawah commented
I think this is ready for review, there is a bunch of updates and fixes (notably viscera seer only coming from one drop)

the main missing groups are the drops with the jumpstart lands and slivers, I started filling a few but then realized it was getting messy and inaccurate so I'd rather start with these

here are some notes from taw/mtgwiki of the missing sets if anybody has more information
[sld notes.txt](https://github.com/user-attachments/files/16114478/sld.notes.txt)

2024-07-06 00:21 UTC, kodawah commented
oh the checks are failing because the boosters are not loaded in yet

2024-07-06 02:18 UTC, axxroytovu requested changes

2024-07-06 02:18 UTC, axxroytovu commented on data/contents/SLD.yaml
> +    - name: stainedglass-tattoo
This is breaking because it should be `code` not `name`

2024-07-06 02:18 UTC, axxroytovu commented on data/contents/SLD.yaml
> +    - name: stainedglass-iwd
Same here - should be `code` and not `name`

2024-07-07 01:07 UTC, kodawah commented on data/contents/SLD.yaml
> +    - name: stainedglass-tattoo
thanks for spotting, updated!

2024-07-07 01:07 UTC, kodawah commented on data/contents/SLD.yaml
> +    - name: stainedglass-iwd
fixed too

2024-07-07 01:50 UTC, axxroytovu approved these changes

2024-07-07 01:51 UTC, merged